# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/liumingyuan/spacemit_robotis/components/mlink_device

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/liumingyuan/spacemit_robotis/components/mlink_device

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liumingyuan/spacemit_robotis/components/mlink_device/CMakeFiles /home/liumingyuan/spacemit_robotis/components/mlink_device//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liumingyuan/spacemit_robotis/components/mlink_device/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MlinkDevice

# Build rule for target.
MlinkDevice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MlinkDevice
.PHONY : MlinkDevice

# fast build rule for target.
MlinkDevice/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/build
.PHONY : MlinkDevice/fast

#=============================================================================
# Target rules for targets named mlink_device_mlink_test

# Build rule for target.
mlink_device_mlink_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlink_device_mlink_test
.PHONY : mlink_device_mlink_test

# fast build rule for target.
mlink_device_mlink_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/mlink_device_mlink_test.dir/build.make test/CMakeFiles/mlink_device_mlink_test.dir/build
.PHONY : mlink_device_mlink_test/fast

#=============================================================================
# Target rules for targets named mlink_device_test_e2e

# Build rule for target.
mlink_device_test_e2e: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mlink_device_test_e2e
.PHONY : mlink_device_test_e2e

# fast build rule for target.
mlink_device_test_e2e/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/mlink_device_test_e2e.dir/build.make test/CMakeFiles/mlink_device_test_e2e.dir/build
.PHONY : mlink_device_test_e2e/fast

core/mcp/mcp_property.o: core/mcp/mcp_property.c.o
.PHONY : core/mcp/mcp_property.o

# target to build an object file
core/mcp/mcp_property.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_property.c.o
.PHONY : core/mcp/mcp_property.c.o

core/mcp/mcp_property.i: core/mcp/mcp_property.c.i
.PHONY : core/mcp/mcp_property.i

# target to preprocess a source file
core/mcp/mcp_property.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_property.c.i
.PHONY : core/mcp/mcp_property.c.i

core/mcp/mcp_property.s: core/mcp/mcp_property.c.s
.PHONY : core/mcp/mcp_property.s

# target to generate assembly for a file
core/mcp/mcp_property.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_property.c.s
.PHONY : core/mcp/mcp_property.c.s

core/mcp/mcp_return_value.o: core/mcp/mcp_return_value.c.o
.PHONY : core/mcp/mcp_return_value.o

# target to build an object file
core/mcp/mcp_return_value.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_return_value.c.o
.PHONY : core/mcp/mcp_return_value.c.o

core/mcp/mcp_return_value.i: core/mcp/mcp_return_value.c.i
.PHONY : core/mcp/mcp_return_value.i

# target to preprocess a source file
core/mcp/mcp_return_value.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_return_value.c.i
.PHONY : core/mcp/mcp_return_value.c.i

core/mcp/mcp_return_value.s: core/mcp/mcp_return_value.c.s
.PHONY : core/mcp/mcp_return_value.s

# target to generate assembly for a file
core/mcp/mcp_return_value.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_return_value.c.s
.PHONY : core/mcp/mcp_return_value.c.s

core/mcp/mcp_server.o: core/mcp/mcp_server.c.o
.PHONY : core/mcp/mcp_server.o

# target to build an object file
core/mcp/mcp_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_server.c.o
.PHONY : core/mcp/mcp_server.c.o

core/mcp/mcp_server.i: core/mcp/mcp_server.c.i
.PHONY : core/mcp/mcp_server.i

# target to preprocess a source file
core/mcp/mcp_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_server.c.i
.PHONY : core/mcp/mcp_server.c.i

core/mcp/mcp_server.s: core/mcp/mcp_server.c.s
.PHONY : core/mcp/mcp_server.s

# target to generate assembly for a file
core/mcp/mcp_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_server.c.s
.PHONY : core/mcp/mcp_server.c.s

core/mcp/mcp_server_protocol.o: core/mcp/mcp_server_protocol.c.o
.PHONY : core/mcp/mcp_server_protocol.o

# target to build an object file
core/mcp/mcp_server_protocol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_server_protocol.c.o
.PHONY : core/mcp/mcp_server_protocol.c.o

core/mcp/mcp_server_protocol.i: core/mcp/mcp_server_protocol.c.i
.PHONY : core/mcp/mcp_server_protocol.i

# target to preprocess a source file
core/mcp/mcp_server_protocol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_server_protocol.c.i
.PHONY : core/mcp/mcp_server_protocol.c.i

core/mcp/mcp_server_protocol.s: core/mcp/mcp_server_protocol.c.s
.PHONY : core/mcp/mcp_server_protocol.s

# target to generate assembly for a file
core/mcp/mcp_server_protocol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_server_protocol.c.s
.PHONY : core/mcp/mcp_server_protocol.c.s

core/mcp/mcp_tool.o: core/mcp/mcp_tool.c.o
.PHONY : core/mcp/mcp_tool.o

# target to build an object file
core/mcp/mcp_tool.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_tool.c.o
.PHONY : core/mcp/mcp_tool.c.o

core/mcp/mcp_tool.i: core/mcp/mcp_tool.c.i
.PHONY : core/mcp/mcp_tool.i

# target to preprocess a source file
core/mcp/mcp_tool.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_tool.c.i
.PHONY : core/mcp/mcp_tool.c.i

core/mcp/mcp_tool.s: core/mcp/mcp_tool.c.s
.PHONY : core/mcp/mcp_tool.s

# target to generate assembly for a file
core/mcp/mcp_tool.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mcp/mcp_tool.c.s
.PHONY : core/mcp/mcp_tool.c.s

core/mlink.o: core/mlink.c.o
.PHONY : core/mlink.o

# target to build an object file
core/mlink.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mlink.c.o
.PHONY : core/mlink.c.o

core/mlink.i: core/mlink.c.i
.PHONY : core/mlink.i

# target to preprocess a source file
core/mlink.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mlink.c.i
.PHONY : core/mlink.c.i

core/mlink.s: core/mlink.c.s
.PHONY : core/mlink.s

# target to generate assembly for a file
core/mlink.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/mlink.c.s
.PHONY : core/mlink.c.s

core/posix/background_sched.o: core/posix/background_sched.c.o
.PHONY : core/posix/background_sched.o

# target to build an object file
core/posix/background_sched.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/background_sched.c.o
.PHONY : core/posix/background_sched.c.o

core/posix/background_sched.i: core/posix/background_sched.c.i
.PHONY : core/posix/background_sched.i

# target to preprocess a source file
core/posix/background_sched.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/background_sched.c.i
.PHONY : core/posix/background_sched.c.i

core/posix/background_sched.s: core/posix/background_sched.c.s
.PHONY : core/posix/background_sched.s

# target to generate assembly for a file
core/posix/background_sched.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/background_sched.c.s
.PHONY : core/posix/background_sched.c.s

core/posix/event_group.o: core/posix/event_group.c.o
.PHONY : core/posix/event_group.o

# target to build an object file
core/posix/event_group.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/event_group.c.o
.PHONY : core/posix/event_group.c.o

core/posix/event_group.i: core/posix/event_group.c.i
.PHONY : core/posix/event_group.i

# target to preprocess a source file
core/posix/event_group.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/event_group.c.i
.PHONY : core/posix/event_group.c.i

core/posix/event_group.s: core/posix/event_group.c.s
.PHONY : core/posix/event_group.s

# target to generate assembly for a file
core/posix/event_group.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/event_group.c.s
.PHONY : core/posix/event_group.c.s

core/posix/list.o: core/posix/list.c.o
.PHONY : core/posix/list.o

# target to build an object file
core/posix/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/list.c.o
.PHONY : core/posix/list.c.o

core/posix/list.i: core/posix/list.c.i
.PHONY : core/posix/list.i

# target to preprocess a source file
core/posix/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/list.c.i
.PHONY : core/posix/list.c.i

core/posix/list.s: core/posix/list.c.s
.PHONY : core/posix/list.s

# target to generate assembly for a file
core/posix/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/list.c.s
.PHONY : core/posix/list.c.s

core/posix/mutex.o: core/posix/mutex.c.o
.PHONY : core/posix/mutex.o

# target to build an object file
core/posix/mutex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/mutex.c.o
.PHONY : core/posix/mutex.c.o

core/posix/mutex.i: core/posix/mutex.c.i
.PHONY : core/posix/mutex.i

# target to preprocess a source file
core/posix/mutex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/mutex.c.i
.PHONY : core/posix/mutex.c.i

core/posix/mutex.s: core/posix/mutex.c.s
.PHONY : core/posix/mutex.s

# target to generate assembly for a file
core/posix/mutex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/mutex.c.s
.PHONY : core/posix/mutex.c.s

core/posix/queue.o: core/posix/queue.c.o
.PHONY : core/posix/queue.o

# target to build an object file
core/posix/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/queue.c.o
.PHONY : core/posix/queue.c.o

core/posix/queue.i: core/posix/queue.c.i
.PHONY : core/posix/queue.i

# target to preprocess a source file
core/posix/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/queue.c.i
.PHONY : core/posix/queue.c.i

core/posix/queue.s: core/posix/queue.c.s
.PHONY : core/posix/queue.s

# target to generate assembly for a file
core/posix/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/queue.c.s
.PHONY : core/posix/queue.c.s

core/posix/schedule.o: core/posix/schedule.c.o
.PHONY : core/posix/schedule.o

# target to build an object file
core/posix/schedule.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/schedule.c.o
.PHONY : core/posix/schedule.c.o

core/posix/schedule.i: core/posix/schedule.c.i
.PHONY : core/posix/schedule.i

# target to preprocess a source file
core/posix/schedule.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/schedule.c.i
.PHONY : core/posix/schedule.c.i

core/posix/schedule.s: core/posix/schedule.c.s
.PHONY : core/posix/schedule.s

# target to generate assembly for a file
core/posix/schedule.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/schedule.c.s
.PHONY : core/posix/schedule.c.s

core/posix/sys_time.o: core/posix/sys_time.c.o
.PHONY : core/posix/sys_time.o

# target to build an object file
core/posix/sys_time.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/sys_time.c.o
.PHONY : core/posix/sys_time.c.o

core/posix/sys_time.i: core/posix/sys_time.c.i
.PHONY : core/posix/sys_time.i

# target to preprocess a source file
core/posix/sys_time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/sys_time.c.i
.PHONY : core/posix/sys_time.c.i

core/posix/sys_time.s: core/posix/sys_time.c.s
.PHONY : core/posix/sys_time.s

# target to generate assembly for a file
core/posix/sys_time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/sys_time.c.s
.PHONY : core/posix/sys_time.c.s

core/posix/task.o: core/posix/task.c.o
.PHONY : core/posix/task.o

# target to build an object file
core/posix/task.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/task.c.o
.PHONY : core/posix/task.c.o

core/posix/task.i: core/posix/task.c.i
.PHONY : core/posix/task.i

# target to preprocess a source file
core/posix/task.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/task.c.i
.PHONY : core/posix/task.c.i

core/posix/task.s: core/posix/task.c.s
.PHONY : core/posix/task.s

# target to generate assembly for a file
core/posix/task.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/task.c.s
.PHONY : core/posix/task.c.s

core/posix/utils.o: core/posix/utils.c.o
.PHONY : core/posix/utils.o

# target to build an object file
core/posix/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/utils.c.o
.PHONY : core/posix/utils.c.o

core/posix/utils.i: core/posix/utils.c.i
.PHONY : core/posix/utils.i

# target to preprocess a source file
core/posix/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/utils.c.i
.PHONY : core/posix/utils.c.i

core/posix/utils.s: core/posix/utils.c.s
.PHONY : core/posix/utils.s

# target to generate assembly for a file
core/posix/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/posix/utils.c.s
.PHONY : core/posix/utils.c.s

core/transport/hwio/tcp.o: core/transport/hwio/tcp.c.o
.PHONY : core/transport/hwio/tcp.o

# target to build an object file
core/transport/hwio/tcp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/transport/hwio/tcp.c.o
.PHONY : core/transport/hwio/tcp.c.o

core/transport/hwio/tcp.i: core/transport/hwio/tcp.c.i
.PHONY : core/transport/hwio/tcp.i

# target to preprocess a source file
core/transport/hwio/tcp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/transport/hwio/tcp.c.i
.PHONY : core/transport/hwio/tcp.c.i

core/transport/hwio/tcp.s: core/transport/hwio/tcp.c.s
.PHONY : core/transport/hwio/tcp.s

# target to generate assembly for a file
core/transport/hwio/tcp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/transport/hwio/tcp.c.s
.PHONY : core/transport/hwio/tcp.c.s

core/transport/hwio/unix.o: core/transport/hwio/unix.c.o
.PHONY : core/transport/hwio/unix.o

# target to build an object file
core/transport/hwio/unix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/transport/hwio/unix.c.o
.PHONY : core/transport/hwio/unix.c.o

core/transport/hwio/unix.i: core/transport/hwio/unix.c.i
.PHONY : core/transport/hwio/unix.i

# target to preprocess a source file
core/transport/hwio/unix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/transport/hwio/unix.c.i
.PHONY : core/transport/hwio/unix.c.i

core/transport/hwio/unix.s: core/transport/hwio/unix.c.s
.PHONY : core/transport/hwio/unix.s

# target to generate assembly for a file
core/transport/hwio/unix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/transport/hwio/unix.c.s
.PHONY : core/transport/hwio/unix.c.s

core/transport/transport.o: core/transport/transport.c.o
.PHONY : core/transport/transport.o

# target to build an object file
core/transport/transport.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/transport/transport.c.o
.PHONY : core/transport/transport.c.o

core/transport/transport.i: core/transport/transport.c.i
.PHONY : core/transport/transport.i

# target to preprocess a source file
core/transport/transport.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/transport/transport.c.i
.PHONY : core/transport/transport.c.i

core/transport/transport.s: core/transport/transport.c.s
.PHONY : core/transport/transport.s

# target to generate assembly for a file
core/transport/transport.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MlinkDevice.dir/build.make CMakeFiles/MlinkDevice.dir/core/transport/transport.c.s
.PHONY : core/transport/transport.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... MlinkDevice"
	@echo "... mlink_device_mlink_test"
	@echo "... mlink_device_test_e2e"
	@echo "... core/mcp/mcp_property.o"
	@echo "... core/mcp/mcp_property.i"
	@echo "... core/mcp/mcp_property.s"
	@echo "... core/mcp/mcp_return_value.o"
	@echo "... core/mcp/mcp_return_value.i"
	@echo "... core/mcp/mcp_return_value.s"
	@echo "... core/mcp/mcp_server.o"
	@echo "... core/mcp/mcp_server.i"
	@echo "... core/mcp/mcp_server.s"
	@echo "... core/mcp/mcp_server_protocol.o"
	@echo "... core/mcp/mcp_server_protocol.i"
	@echo "... core/mcp/mcp_server_protocol.s"
	@echo "... core/mcp/mcp_tool.o"
	@echo "... core/mcp/mcp_tool.i"
	@echo "... core/mcp/mcp_tool.s"
	@echo "... core/mlink.o"
	@echo "... core/mlink.i"
	@echo "... core/mlink.s"
	@echo "... core/posix/background_sched.o"
	@echo "... core/posix/background_sched.i"
	@echo "... core/posix/background_sched.s"
	@echo "... core/posix/event_group.o"
	@echo "... core/posix/event_group.i"
	@echo "... core/posix/event_group.s"
	@echo "... core/posix/list.o"
	@echo "... core/posix/list.i"
	@echo "... core/posix/list.s"
	@echo "... core/posix/mutex.o"
	@echo "... core/posix/mutex.i"
	@echo "... core/posix/mutex.s"
	@echo "... core/posix/queue.o"
	@echo "... core/posix/queue.i"
	@echo "... core/posix/queue.s"
	@echo "... core/posix/schedule.o"
	@echo "... core/posix/schedule.i"
	@echo "... core/posix/schedule.s"
	@echo "... core/posix/sys_time.o"
	@echo "... core/posix/sys_time.i"
	@echo "... core/posix/sys_time.s"
	@echo "... core/posix/task.o"
	@echo "... core/posix/task.i"
	@echo "... core/posix/task.s"
	@echo "... core/posix/utils.o"
	@echo "... core/posix/utils.i"
	@echo "... core/posix/utils.s"
	@echo "... core/transport/hwio/tcp.o"
	@echo "... core/transport/hwio/tcp.i"
	@echo "... core/transport/hwio/tcp.s"
	@echo "... core/transport/hwio/unix.o"
	@echo "... core/transport/hwio/unix.i"
	@echo "... core/transport/hwio/unix.s"
	@echo "... core/transport/transport.o"
	@echo "... core/transport/transport.i"
	@echo "... core/transport/transport.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

